### ISSUE TITLE
Refactor documentation to avoid full links

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/flask-utils#10]
Refactor documentation to avoid full links in docs (have `BadRequestError` instead of `flask_utils.errors.BadRequestError`).

For example https://flask-utils.readthedocs.io/en/latest/api.html#custom-exceptions
<img width="725" alt="Screenshot 2024-06-10 at 14 50 02" src="https://github.com/Seluj78/flask-utils/assets/4641317/6c589fd2-58a3-4db4-9460-33c156bb23b7">

**Comment by Mews** [comment]
In your example, would you rather `flask_utils.errors.BadRequestError` become `flask_utils.BadRequestError` or just `BadRequestError`

**Comment by Seluj78** [comment]
Yeah I want to have the link to just be `BadRequestError` using `:meth:` or `:func:` but I wasn't able to do it and I am not knowledgable enough in Sphinx

**Comment by Mews** [comment]
Ok so just to make sure you want to change this
![image](https://github.com/Seluj78/flask-utils/assets/60406199/409a880f-254c-40f8-925f-defa4b6f6d47)
To this
![image](https://github.com/Seluj78/flask-utils/assets/60406199/1c9aa0b0-694e-4b72-ab2e-c1428c7d6871)

**Comment by Seluj78** [comment]
Thanks totally correct ;

**Comment by Mews** [comment]
Alright I think that's a single line of code lol
But I'll open the pr anyway
