### ISSUE TITLE
Add all-contributors to readme and project

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/flask-utils#32]
https://github.com/all-contributors/app

**Comment by Mews** [comment]
I don't know all the functionality that this all-contributors app gives, but at least for the readme, if you just want to have something like this
![image](https://github.com/Seluj78/flask-utils/assets/60406199/e52bde77-f11b-4a30-a56e-544fe62ef024)
It can be done without any extra apps or anything

**Comment by Seluj78** [comment]
Yes totally, but the idea of `all-contributors` is that it handles the README part for you ! :D

https://allcontributors.org/

**Comment by Seluj78** [comment]
Not not really, I'll show you :)

**Comment by Seluj78** [comment]
@all-contributors please add @Mews for doc

**Comment by Mews** [comment]
I'm pretty sure it auto updates if you use a service like https://contrib.rocks/ to generate the image, but nice

**Comment by Seluj78** [comment]
True, but I've use @all-contributors in the past and I enjoy it :) Check out the readme !

**Comment by Mews** [comment]
Yeah it looks nice, the https://contrib.rocks/ only shows the profile pics of the contributors

**Comment by Seluj78** [comment]
@all-contributors please add @Seluj78 for code, doc, infra, example, mentoring, platform, projectManagement, review, tutorial

**Comment by Mews** [comment]
Btw isn't this issue resolved then?

**Comment by Seluj78** [comment]
Totally lol
